### PR TITLE
Automatically generate docs via rustdoc upon git push

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
I already added my github token as `TOKEN` in travis-ci, all that's left to do is to merge

**Comment by sunng87** [comment]
LGTM :+1:

**Comment by frewsxcv** [comment]
This should work once the build finishes I think

https://travis-ci.org/georust/rust-geohash/builds

**Comment by frewsxcv** [comment]
@sunng87 Have you ever been able to build documentation for this project? I can't seem to do it locally with rustdoc. I wonder if this is a bug with rustdoc

**Comment by frewsxcv** [comment]
https://github.com/georust/rust-geohash/blob/302b3e06c535a8639806b8260bcff64f5429bf83/src/lib.rs#L1-L2

If you comment out those two lines, the documentation builds fine. I think that's a bug?

**Comment by sunng87** [comment]
@frewsxcv `cargo doc` exits without error. But no docs generated. I will move tests into separated module then.

**Comment by frewsxcv** [comment]
This should fix the docs issue: https://github.com/georust/rust-geohash/pull/5

**Comment by frewsxcv** [comment]
Working now https://georust.github.io/rust-geohash/geohash/index.html

**Comment by sunng87** [comment]
Yay!

**Pull request merged**
